name: CI

on:
  pull_request:
  push:
    branches:
      - appmap-e2e
  schedule:
    - cron: "0 0 * * 0"

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout step
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "8"
          cache: "maven"

      - name: Install AppMap tools
        uses: getappmap/install-action@v1
        with:
          project-type: maven
          install-appmap-library: false
          tools-url: https://github.com/getappmap/appmap-js/releases/download/%40appland%2Fappmap-bm25-10e1c36e/appmap-linux-x64

      - name: Build and test
        run: ./mvnw --no-transfer-progress test

      - name: Move AppMaps to standard location
        run: mkdir -p tmp && mv target/appmap tmp/

      - name: Build BM25 index of the source code
        run: appmap index --bm25 tmp/appmap/lunr.json

      - name: Archive AppMaps
        uses: getappmap/archive-action@v1
