name: CI

on:
  pull_request:
  push:
    branches:
      - appmap-e2e
  schedule:
    - cron: "0 0 * * 0"

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout step
        uses: actions/checkout@v3

      - name: Docker build target=source
        run: docker build --target source -t spring-petclinic .

      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "8"
          cache: "maven"

      - name: Install AppMap tools
        uses: getappmap/install-action@v1
        with:
          project-type: maven
          install-appmap-library: false
          tools-url: https://github.com/getappmap/appmap-js/releases/download/%40appland%2Fappmap-context-api.26fbdf21/appmap-linux-x64

      - name: Build and test
        run: ./mvnw --no-transfer-progress test

      - name: Collect and index AppMaps
        run: |
          mkdir -p tmp && mv target/appmap tmp/
          appmap index

      - name: Docker build target=appmaps
        run: docker build --target appmaps -t spring-petclinic .

      - name: Docker build (final)
        run: |
          cp -r /usr/local/bin/appmap .
          docker build --target final -t spring-petclinic .

      - name: Push to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
          heroku container:login
          heroku container:push -a aictx-spring-petclinic web
          heroku container:release -a aictx-spring-petclinic web
